### ISSUE TITLE
bug in mol.sum when there's single gene

### ISSUE THREAD

**Issue by easygsea** [datapplab/pathview#2]
Hi there,

When the input data end up with only one gene, it errored out in id.map

Would be helpful if you could fix that, by adding drop=F:

id.map=id.map[sel.idx,,drop=F]

Thanks!

**Comment by wluo1** [comment]
Dear easygsea,
Thanks for reporting the issue. This has been fixed in VERSION 1.31.3/1.30.3
https://github.com/datapplab/pathview/blob/master/NEWS

**Comment by easygsea** [comment]
That’s awesome! Thank you for prompt fixing!
