### ISSUE TITLE
Printing the Pathview Output on RMarkdown Document

### ISSUE THREAD

**Issue by canholyavkin** [datapplab/pathview#20]
I'm using pathview on the Rmarkdown document. However, `pathview()` just saves a plot into the current directory. Is it possible to display the output of `pathview()` directly in R?

**Comment by joseale2310** [comment]
I would also like to know how to save all the results to another directory. Setting `kegg.dir = "../Results/"` only saves the png and xml, but the "Id.pathway.png" image is still saved in the current directory!

**Comment by joseale2310** [comment]
@canholyavkin You could use knitr::include_graphics("path/to/pathway.png") to see the result in the Rmarkdown

**Comment by canholyavkin** [comment]
> @canholyavkin You could use knitr::include_graphics("path/to/pathway.png") to see the result in the Rmarkdown

Unfortunately, I also execute the pathway analysis on the same RMarkdown, so the png images are not generated at the beginning of the render. So, as the R couldn't find the png images in the first check, it just gives an error.

**Comment by raw937** [comment]
Are you still having this issue?

This project is no longer under development here.
Please check the new fork here.
https://github.com/Kannapolis-Bioinformatics/pathview

If you have the same issues place in:
https://github.com/Kannapolis-Bioinformatics/pathview/issues

many thanks,
Rick

**Comment by canholyavkin** [comment]
I'll check the issue again and if it persists I'll open a case at new repo. Thanks.

**Comment by joseale2310** [comment]
Somehow I cannot place issues there, only pull requests! Are issues disabled in the repo? https://github.com/Kannapolis-Bioinformatics/pathview/

**Comment by raw937** [comment]
Fixed now.
