### ISSUE TITLE
Pathview fails with unhelpful error message when limit is set to two equal values

### ISSUE THREAD

**Issue by lumotroph** [datapplab/pathview#3]
When running the following:
```r
  pv_out = pathview(
    gene.data = pathway_lfc_entrez_matrix,
    pathway.id = pathway,
    species = "hsa",
    same.layer = TRUE,
    limit = list(
      gene = c(pathway_lowest_lfc, pathway_highest_lfc),
      cpd = c(1, 1)
    ),
    both.dirs = TRUE
  )
```

The pathview function will crash _only on some pathways_. 

This is caused by the `cpd = c(1, 1)` parameter having two of the same values.

See my issue (fixed) [here](https://support.bioconductor.org/p/9137064/) for more details

Thanks for a great tool!

**Comment by wluo1** [comment]
Dear Duncan,
I guess it would be safer to leave cpd limit unset (default values) when there is no cpd data. 
But thanks for reporting the issue and the post. This is helpful for other uses.
