### ISSUE TITLE
ask for help about the function of pathview

### ISSUE THREAD

**Issue by sjtuyf** [datapplab/pathview#5]
Dear "pathview" team,

Thank you very much to develop the R package "pathview". Now I meet one problem with this package, and I wish to get some help from you.

I have plotted the non-native KEGG plot with the pathview function with the script below. It run cuccessfully. However，I do not want show the color key in the non-native KEGG plot. I tried to check the parameter in the pathview function，which decide color key is added or not，but found none. Additionaly, I find the function of keggview.native，which included the "plot.col.key = TRUE" parameter. I tried to included the "plot.col.key = FALSE" in the script below of pathview, however, it failed. 

So I am wondering how can i set of the script below to ensure the colour key is not shown in the non-native KEGG plot.
I really want to get your help if possible.

At last, hope your project goes well and the best wishes to you.
I am looking forward to your reply. Thanks a lot.

Yours sincerely
Yafei

###the script to output the non-native KEGG plot
real_data <- read.csv("real_data.csv", row.names=1)
p <- pathview(gene.data = real_data,
               pathway.id = "00640", species = "ko", out.suffix = "ko00640",
               keys.align = "y", kegg.native = T, match.data = F, multi.state = T,
               same.layer = T,low = list(gene = "purple"), mid = list(gene = "lightblue1"), high = list(gene = "orange"))

**Comment by wluo1** [comment]
Dear Yifei,
I was not able to replicae your problem, and I did get the non-native KEGG plot without the color key as attached. I used the code below.

```
library(pathview)
gdata=sim.mol.data(mol.type="gene", species="ko", nmol=10000, nexp=2)
pv.out=pathview(gene.data = gdata, pathway.id = "00640", species = "ko", kegg.native = F, plot.col.key=F)

```

![image](https://user-images.githubusercontent.com/36652110/121410923-15b9a300-c931-11eb-87e6-93fb42709b3a.png)

**Comment by sjtuyf** [comment]
> Dear Yifei,
> I was not able to replicae your problem, and I did get the non-native KEGG plot without the color key as attached. I used the code below.
> 
> ```
> library(pathview)
> gdata=sim.mol.data(mol.type="gene", species="ko", nmol=10000, nexp=2)
> pv.out=pathview(gene.data = gdata, pathway.id = "00640", species = "ko", kegg.native = F, plot.col.key=F)
> ```
> 
> ![image](https://user-images.githubusercontent.com/36652110/121410923-15b9a300-c931-11eb-87e6-93fb42709b3a.png)

Dear "pathview" team,

Thank you for your quick reply. I tried your code，get the non-native KEGG plot without the color key as attached. 

I am sorry I do not tell clear yesterday. The plot I want is the native KEGG graph (.png) with genes of custom colors. And I do not want the color key to be shown in the plot. For example, this is one plot with default colour:

library(pathview)
gdata=sim.mol.data(mol.type="gene", species="ko", nmol=10000, nexp=2)
pv.out=pathview(gene.data = gdata, pathway.id = "00640", species = "ko", out.suffix = "ko00640_plot1", kegg.native = T, plot.col.key=F)

![image](https://user-images.githubusercontent.com/35675883/121470165-5e846100-c9f0-11eb-8519-fc3d5e15052e.png)

This is another plot with custom colors:

library(pathview)
gdata=sim.mol.data(mol.type="gene", species="ko", nmol=10000, nexp=2)
pv.out=pathview(gene.data = gdata, pathway.id = "00640", species = "ko", out.suffix = "ko00640_plot2", kegg.native = T, plot.col.key=F,low = list(gene = "purple"), mid = list(gene = "lightblue1"), high = list(gene = "orange"))

![image](https://user-images.githubusercontent.com/35675883/121470234-7e1b8980-c9f0-11eb-8b05-8b6f9667a2ad.png)

My question is how to modify the code in the second plot to make sure the color key is not shown. Can you help me with that？

Thanks again.


Yours sincerely
Yafei

**Comment by wluo1** [comment]
I was not able to reproduce your problem custom colors. The right colors were plotted with the key when plot.col.key=T, and no key color shown when plot.col.key=F.
If the problem you descirbed is real, it would have been reported a long time ago.
If you are serious, I would suggest you to check on your installation of pathview, make sure the code has not been messed up in some way, and reinstall it if needed.

![image](https://user-images.githubusercontent.com/36652110/122110677-d4bc0580-cdec-11eb-9fd4-1b470e9c476a.png)

**Comment by sjtuyf** [comment]
> I was not able to reproduce your problem custom colors. The right colors were plotted with the key when plot.col.key=T, and no key color shown when plot.col.key=F.
> If the problem you descirbed is real, it would have been reported a long time ago.
> If you are serious, I would suggest you to check on your installation of pathview, make sure the code has not been messed up in some way, and reinstall it if needed.
> 
> ![image](https://user-images.githubusercontent.com/36652110/122110677-d4bc0580-cdec-11eb-9fd4-1b470e9c476a.png)

Dear "pathview" team,

Thank you for your suggestion. It worked when I reinstall the package, and run again.

Thanks.

Best
Yafei
